language: node_js

node_js:
  - 7
  - 6

before_install:
  - npm -g i npm@latest

before_script:
  - npm -g i gulp-cli jest-cli && npm -D i ts-jest@0.1.8

script:
  - gulp ci

sudo: false

notifications:
  email: false
