language: node_js

node_js:
  - 7
  - 6

before_install:
  - npm -g i npm@latest

before_script:
  - npm -g i gulp-cli jest-cli

script:
  - jest --coverage --no-cache

sudo: false

notifications:
  email: false
